#!/bin/sh

print_message() {
  # first message
    echo "Please login as 'root' (no password)"
    echo "    use 'setup-finish' to finalize setup."
    echo ""

    local assigned_inets=$(ip -o addr show | grep -v ' lo '| awk '{print $4}')

    if [ -z "${assigned_inets}" ]; then
        echo "No IPs assigned"
    else
        echo "Assigned IPs: "
        IFS=$'\n'
        for inet_addr in $assigned_inets; do
            echo "    - $inet_addr"
        done
    fi

    echo ""

    [[ -s /home/master/.ssh/authorized_keys ]] && MASTER_SSH_KEYS_ON=1 || true
    [[ -s /root/.ssh/authorized_keys ]] && ROOT_SSH_KEYS_ON=1 || true

    if [ ! -z $MASTER_SSH_KEYS_ON ] || [ ! -z $ROOT_SSH_KEYS_ON ]; then
        echo "'authorized_keys' found, you can login: "
        [ ! -z $MASTER_SSH_KEYS_ON ] && \
            echo "    ssh -i key_path master@<box ip>" || true

        [ ! -z $ROOT_SSH_KEYS_ON ] && \
            echo "    ssh -i key_path root@<box ip>" || true

        echo ""
    fi
}

if [ "$(tty)" != "/dev/tty1" ] || [ "$1" == "printanyway" ]; then
    print_message
fi

exit 0
