#!/bin/sh

[ -n "$PRETEND" ] && [[ $(echo "$PRETEND" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        RUN="echo" || RUN=

[ -n "$DEBUG" ] && [[ $(echo "$DEBUG" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        set -xe || set -e


function include_all() {
  readonly SCRIPT_PATH=$1
  readonly SCRIPT_BASE=$(basename $1)
  readonly SCRIPT_DIR=$(dirname $1)

  for script in $(ls ${SCRIPT_DIR}/${SCRIPT_BASE}-* 2>/dev/null); do
    if [ -x $script ]; then
      source $script
    fi
  done
}

export RUN
export DEBUG

export ARGS="$@"
include_all $0


# Global variables:
# From parameters:
_MODE=

_IMG_BOOT=0
_NO_PART_TABLE_MODE=-1

_DEV_MODEL=
_MACHINE=$_DEV_MODEL

_IMG_FILE=
_KERNEL=vmlinuz
_INITRAMFS=

_PERMANENT_CONTAINER=0
_CONTAINER_NAME=
_OPTION_DETACH=1

_LIST_WITH_DETAILS=0

# Run-time globals
_LOBOOT_DEV=

# connection:
SSH_GUEST_PORT=15022
SSH_DEF_PRIV_KEY_NAME=id_ed25519

CONTAINER_SSH_KEY_PATH=

# shellcheck disable=SC2112
function print_help() {
    cat <<EOF
Usage:
Creating container:
$SCRIPT_BASE --device|-d [raspi3b] <img file> [+SIZE] --imgboot|-i y|n <kernel> <initramfs> --name|-n <name>

  --device|-d      - Model of the emulated device (default: '${_carg_create_dev_name_param}').
  <img file>       - Path to image file to be mounted as 'mmcblk0'.
  --imgboot|-i y|n - If 'y' load <kernel> and <initramfs> from a boot
                     partition of the image file.
                     If 'n' load <kernel> and <initramfs> from file.
                     <kernel>    - Path to kernel, if '-i y' path within
                                   boot partition of the image file.
                                   If '-i n' path to kernel file that is
                                   located at host.
                     <initramfs> - Path to initramfs, if '-i y' path within
                                   boot partition of the image file.
                                   If '-i n' path to initramfs file that is
                                   located at host.
                     Initramfs is optional, if not provided emulated system
                     will boot with just kernel image. It means that kernel
                     must have all modules to mount root fs as well as to
                     access necessary devices such as disk controller.

                     Also, <kernel> path might be skiped, in this case default
                     '${_KERNEL}' is loaded from boot image file partition
                     (if '-i y'), or current directory of a local file system
                     (if '-i n'). In this case initramfs can't be used.

  --name|-n        - Create named container, in option '-n' is followed by
                     <name> container with a given name is created.
                     If only option '-n' is provided container with random name
                     is created, name of the container is displayed upon launch.

                     If option '-n' is not provided then temporary container is
                     created - it will be removed after machine is stopped.

Launching container:
$SCRIPT_BASE <container name> [--wait|-w]
  This will launch container that has been created from an image.
  --wait|-w    wait until guest os is up.

Guest interaction:
$SCRIPT_BASE command <command to be exiecuted in guest>
  This will launch provided command (over SSH) in VM.

$SCRIPT_BASE sync <host source dir> [<guest target dir>] --reverse|-r
  This will synchronize local file or directory with a location on guest
  system (over SSH). <guest target dir> can be skipped, if so default location
  is '/usr/local/bin'.
  --reverse|-r    Synchronize guest location with a host local directory (reversed
                  order)

$SCRIPT_BASE enter|console
  Enter (via ssh) VM guest console.

$SCRIPT_BASE stop
  Shutdown running machine.

$SCRIPT_BASE waitfor
  Wait until machine is responding.

Listing containers:
$SCRIPT_BASE ls --full|-f
  ls - list all defined containers

Attachable (extstore) image operations:
$SCRIPT_BASE extstore [ls --full|-f] | [add <name|path> SIZE] | [eject]
  Container can have virtually attached external ("USB stick") storage.

  extstore ls  - list attachable images
    --full|-f  - list attachable images with details

  extstore add - add 'external' storage to machine, the storage will be
                 available as USB stick. Storage can be identified by a path,
                 or name. If identified by path, '$SCRIPT_BASE' is expecting
                 a file name. Indicated file will be attached to machine as a
                 storage device.
                 If name provided, '$SCRIPT_BASE' will search for an
                 attachable image in its internal storage system.

                 If storage exists, it will be attached to the machine.
                 In order to create storage, non existing image name or path
                 must be provided followed by a size. '$SCRIPT_BASE' will
                 create storage of a given size and attach it to the machine.

                 New storage is automatically initiated with zeros.
                 Default SIZE unit is MiB, SIZE can be postfixed by MiB, MB,
                 GiB, GB e.g.: 2GB

Initialization:
$SCRIPT_BASE init
  Create storage backends, databases etc. for $SCRIPT_BASE

EOF
}


# sd-card size must be of power 2, e.g.:
# 512MiB, 1GiB, 2GiB, 4GiB ...
# Append extra 'zeros' to an end of an
# image file to ensure that its size is
# exactly 2^<power> bites.
function prepare_mmc_imgfile() {
  local IMAGE_PATH="$1"
  local CACHE_FILE="$2"

  if [ ! -f "$CACHE_FILE" ] || [ ! -s "$CACHE_FILE" ] ; then
    # if file does not exists, or is a zero size copy image
    $RUN cp "$IMAGE_PATH" $CACHE_FILE
  fi
  # else, if file already exists veriry size

  CUR_SIZE=$(first_arg $(du -sb $IMAGE_PATH))

  POW=$(( 256*1024*1024 ))

  while [ $POW -lt $CUR_SIZE ]; do
    POW=$(($POW*2))
    #echo $POW
  done

  REM_SIZE_TOPOW=$(($POW - $CUR_SIZE))

  # if zero file is of a proper size already

  if [ $REM_SIZE_TOPOW -ne 0 ]; then
    #echo "Appending file with extra 'zeros' to reach size that is a power of 256 MiB (requirment for SD cards)"
    #echo "Appending by: $REM_SIZE_TOPOW bytes"
    #echo "Final size: $(($REM_SIZE_TOPOW + $CUR_SIZE)) bytes"

    # make file size to be multiple of MB:
    TAIL=$(( ($REM_SIZE_TOPOW % $ONE_MIB) ))

    # init is in bytes
    if [ $TAIL -ne 0 ]; then
      $RUN dd bs=1 seek=$CUR_SIZE if=/dev/zero of=$CACHE_FILE count=$TAIL
    fi

    # change units to MiB
    CUR_SIZE=$(( ($CUR_SIZE + $TAIL) / $ONE_MIB ))
    TAIL=$(($REM_SIZE_TOPOW / $ONE_MIB))

    if [ $TAIL -ne 0 ]; then
      $RUN dd bs=$ONE_MIB seek=$CUR_SIZE if=/dev/zero of=$CACHE_FILE count=$TAIL
    fi
  fi
}

function prepare_usbstick() {
  local PATH=$1
  local SIZE_MB=$2

  $RUN /usr/bin/dd bs=$ONE_MIB count=${SIZE_MB} if="/dev/zero" of="${PATH}"
}

function mount_boot() {
  local WORK_IMG=$1

  # Get available loop device, normally '/dev/loop0'
  if [ -z "$RUN" ]; then
    _LOBOOT_DEV=$(losetup -f)
  else
    _LOBOOT_DEV="/dev/loop0dummy"
  fi
  # Create device for mounting partition that will be used as 'boot'
  $RUN losetup $_LOBOOT_DEV $WORK_IMG
  $RUN partprobe -s $_LOBOOT_DEV

  # mount first partition, or if no partition table mount filesystem directly
  if [ -e ${_LOBOOT_DEV}p1 ]; then
    $RUN mount ${_LOBOOT_DEV}p1 $BOOT_MNT_DIR -o ro || true
    _NO_PART_TABLE_MODE=0

    if findmnt -rno TARGET "${_LOBOOT_DEV}p1" >/dev/null; then
      echo "Partition ${_LOBOOT_DEV}p1 is mounted."
    else
      echo "Falling back to mnount without partition table"
      $RUN mount ${_LOBOOT_DEV} $BOOT_MNT_DIR -o ro
      _NO_PART_TABLE_MODE=1;
    fi
  else
    $RUN mount ${_LOBOOT_DEV} $BOOT_MNT_DIR -o ro
    _NO_PART_TABLE_MODE=1
  fi
}

function umount_boot() {
  $RUN umount ${BOOT_MNT_DIR}
  $RUN losetup -d ${_LOBOOT_DEV}
}


function rm_lock_file() {
  if [ -e "${LOCK_FILE}" ]; then
    rm "${LOCK_FILE}" 2>/dev/null || true
  fi

  return 0
}


# Command line parsing functions:

function set_flag_imgboot() {
  if [ -n "$2" ] && [ "yes_no" == "$2" ]; then
    _IMG_BOOT=$1
  fi
}


_RSYNC_LOCAL=
_RSYNC_REMOTE=/usr/local/bin
_RSYNC_REVERSE=0



function parse_sync_path1() {
  # actually accept anything
  if [ -n "${1}" ]; then
    _RSYNC_LOCAL=$1
    return 1
  fi

  return 0
}

function parse_SYNC_path2() {
  # accept anything
  if [ -n "${1}" ]; then
    _RSYNC_REMOTE=$1
    return 1
  fi

  return 0
}

function parse_reverse_sync() {
  if [ "$1" == "-r" ] || [ "$1" == "--reverse" ]; then
    _RSYNC_REVERSE=1
    # read
    return 1
  fi

  return 0
}

function set_sync() {
  # arg (param, flag) or chain (root chain, param chain, flag chain)

  # skip arg. setters
  if [ $# -eq 2 ]; then
    # accept
    return 1
  fi

  # set flag
  if [ $# -eq 1 ]; then
    # per parameter setter call
    parse_reverse_sync "${1}"
    retval=$?
    return ${retval}
  fi

  # final setter call:
  local l_loc
  local r_loc

  l_loc=$(realpath ${_RSYNC_LOCAL})
  r_loc="${_RSYNC_REMOTE}"

  if [ ! -e ${l_loc} ]; then
    echo "File or directory does not exists!"

    exit 3
  fi
}

function flag_opt() {
  if [ "$1" == "-f" ] || [ "$1" == "--full" ]; then
    _LIST_WITH_DETAILS=1
    return 1
  fi

  return 0
}

# if something default define it:
_EXTSTORAGE_MODE=add
_EXTSTORAGE_REF=
_EXTSTORAGE_REF_ISINTERNAL=
_EXTSTORAGE_SIZE=

function parse_size() {
  local input="$1"
  local number
  local unit
  local result
  local size

  # Use regular expression to match the number and unit (MB, GB, MiB, GiB)
  if [[ "$input" =~ ^([0-9]+(\.[0-9]+)?)\ ?(m|g|M|G|MB|GB|MiB|GiB)$ ]]; then
    number="${BASH_REMATCH[1]}"
    unit="${BASH_REMATCH[3]}"

    case "$unit" in
      m|M|MB)
        result=$(echo "scale=2; $number * 0.953674" | bc)
      ;;
      g|G|GB)
        result=$(echo "scale=2; $number * 953.674" | bc)
      ;;
      MiB)
        result="$number"
      ;;
      GiB)
        result=$(echo "scale=2; $number * 1024" | bc)
      ;;
    esac

    # Round up to the nearest integer using awk
    size=$(echo "$result" | awk '{print ($1 == int($1)) ? $1 : int($1)+1}')
    echo "$size"

    return 0
    #echo "Invalid input. Please provide a number followed by MB, GB, MiB, or GiB."
  fi

  return 1
}


# Parser 'global' variables
# "parse_now", "param_chain" and "setter_fn" has been defined to handle
# variable parameter "chains"
# Once when 'option' has been identified such as 'ls', '--name'
# variables: 'parse_now', 'parse_chain' and 'setter_fn'
# are used to handle variable argument length parsing
# Thus, some options might be optional making command line
# more user friendly.
# parse_now is the
setter_fn=
param_chain=



function carg_set_param() {
  local cname=$1
  local clink=$2
  local value=$3

  if [ -z ${value} ]; then
    # no thing to set
    return 0
  fi

  # declare if value not defined, defined value is a default value
  local param_name="_carg_${cname}_${clink}_param"
  if [ -z ${!param_name} ]; then
    declare -gr "${param_name}=${value}"
  else
    eval "${param_name}=${value}"
  fi
}

function carg_isparam_set() {
  local cname=$1
  local clink=$2
  local var="_carg_${cname}_${clink}_param"

  [ -n "${!var}" ]
  return $?
}

# Return value:
#     0 - argument has been parsed successfully
#     1 - argument can't be interpreted
#
# If parameter is accepted, it must be registered with:
#   carg_set_param function
function parse___autoparam() {
  local cname=$1
  local clink=$2
  local value=$3

  if [ $clink == $value ]; then
    carg_set_param "$cname" $clink 1
    return 0
  fi

  return 1
}


function parse__MODE() {
  local cname=$1
  local clink=$2
  local cmd=$3
  local res=0

  case $cmd in
    command|exec)
      CARG=
      cmd="command"
      _carg_chain_parse "arg*" "COMMAND"
      res=$?
    ;;
    sync)
      CARG=
      _carg_chain_parse "--reverse-r? path_local path_remote?" "SYNC"
      res=$?
    ;;
    enter|console)
      # no parameters
      CARG=
      cmd="console"
    ;;
    stop|waitfor|init)
      # no argumans for these options
      CARG=
    ;;
    ls)
      CARG=
      _carg_chain_parse "--full-f?" $cmd
      res=$?
    ;;
    extstore|es)
      cmd="es"
      CARG=
      _carg_chain_parse "MODE" "ES"
      res=$?
    ;;
    create|run)
      CARG=
      # chain to be called later
    ;;
    *)
      # cmd to be defined later from context
      # it might be run or create
      cmd=
      res=1
    ;;
  esac

  # set value
  carg_set_param "$cname" $clink $cmd

#  [ -n "$cmd" ]
  return $res
}


function parse__CREATE() {
  local res=0

  if [ ! -z $_carg__MODE_param ] && [ "$_carg__MODE_param" != "create" ]; then
    return 1
  fi

  _carg_chain_parse "--device-d? dev_name? file_path extr_size? --imgboot-i yesno kelner? initramfs? --name-n? cont_name?" "CREATE"
  res=$?

  if [ $res -eq 0 ] && [ -z $_carg__MODE_param ]; then
    carg_set_param "" "MODE" "create"
  fi

  return $res
}

_carg_create_dev_name_param=raspi3b
function parse_CREATE_dev_name() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ "$prev_flag" != "d" ] || [ "$prev_flag_dist" != "1" ]; then
    return 1
  fi

  if [[ ! "$name" =~ ^([a-zA-Z0-9\._-]){1,128}$ ]]; then
    echo "Illegal machine (device) name"
    exit 3
  fi

  local machine=$(qemu-system-aarch64 -machine help | grep "^${name}[[:space:]].*")

  if [ -z "$machine" ]; then
    echo "Machine (device) has not been found: $name"
    exit 3
  fi

  # echo "Loading: $machine"
  carg_set_param "$cname" $clink $(first_arg $machine)

  return 0
}

function parse_CREATE_file_path() {
  local cname=$1
  local clink=$2
  local path=$3

  if [ -n "$path" ]; then
    path=$(realpath $path)
    if [ -f $path ]; then
      # set value
      carg_set_param "$cname" $clink $path
      return 0
    fi

    if [ -z $__carg__MODE_param ]; then
      # this will force to try next chain
      return 1
    else
      echo "Provide path to an existing file"
      exit 3
    fi
  fi

  return 1
}

function parse_CREATE_extr_size() {
  local cname=$1
  local clink=$2
  local size="$3"
  local res=

  if [ "${size:0:1}" != '+' ]; then
    return 1
  fi

  size="${size:1}"
  size="$(parse_size "$size")"
  res=$?

  if [ $res -ne 0 ]; then
    echo "Incorrect size format"
    exit 22
  fi

  carg_set_param "$cname" $clink "$size"
  return 0
}

function parse_CREATE_yesno() {
  local cname=$1
  local clink=$2
  local value=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'i' ] || [ $prev_flag_dist -ne 1 ]; then
    return 1
  fi

  if [[ $(echo "$value" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] ; then
    carg_set_param "$cname" $clink true
  elif [[ $(echo "$value" | tr '[:upper:]' '[:lower:]') =~ ^n|no|0|off$ ]] ; then
    carg_set_param "$cname" $clink false
  else
    echo "Correct option is one of: yes, y, on, 1 or no, n, 0, off"
    exit 3
  fi

  return 0
}

# default kernel:
_carg_CREATE_kelner_param=vmlinuz
function parse_CREATE_kelner() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'i' ] || [ $prev_flag_dist -ne 2 ]; then
    return 1
  fi

  if [[ ! "$name" =~ ^([a-zA-Z0-9\._/-]){1,128}$ ]]; then
    echo "Illegal kernel name"
    exit 3
  fi

  carg_set_param "$cname" $clink "$name"
  return 0
}

_carg_CREATE_initramfs_param=
function parse_CREATE_initramfs() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'i' ] || [ $prev_flag_dist -ne 3 ]; then
    return 1
  fi

  if [[ ! "$name" =~ ^([a-zA-Z0-9\._/-]){1,128}$ ]]; then
    echo "Illegal initramfs name"
    exit 3
  fi

  carg_set_param "$cname" $clink "$name"
  return 0
}



function parse_CREATE_cont_name() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'n' ] || [ $prev_flag_dist -ne 1 ]; then
    return 1
  fi

  if ! validate_cont_name "$name"; then
    echo "Illegal name"
    exit 3
  fi
}


function check_CREATE() {
  local err_enc=false

  if [ -z $_carg_CREATE_file_path_param ]; then
    _attach_errormsg "Provide image path" "create"
    err_enc=true
  fi

  if [ -z $_carg_CREATE_yesno_param ]; then
    _attach_errormsg "Define '--imgboot': yes|no" "create"
    err_enc=true
  fi

  if $err_enc; then
    return 1
  fi

  if ! ${_carg_CREATE_yesno_param}; then
    # set realpath
    _carg_CREATE_kelner_param=$(realpath $_carg_CREATE_kelner_param)

    if [ -n "${_carg_CREATE_initramfs_param}" ]; then
      _carg_CREATE_initramfs_param=$(realpath $_carg_CREATE_initramfs_param)
    fi
  fi

  # Create random name if user did not assign
  if [ "${_carg_CREATE_name_flag}" == "1" ] && [ -z ${parse_CREATE_cont_name_param} ]; then
    parse_CREATE_cont_name_param=$(get_random_name)
    echo "Random name assigned: ${parse_CREATE_cont_name_param}"
  fi

  return 0
}

function check_ls() {
  return 0
}

function parse_ES_MODE() {
  local cname=$1
  local clink=$2
  local subcmd=$3
  local res=0

  case $subcmd in
    ls)
      _carg_chain_parse "ls --full-f?" "${cname}_LS"
      res=$?
    ;;
    add)
      _carg_chain_parse "add ref size?" "${cname}_ADD"
      res=$?
    ;;
    eject)
      # no parameters
      CARG=
    ;;
    *)
      echo "Unknown option: $subcmd"
    ;;
  esac

  # set value
  carg_set_param "$cname" $clink $subcmd

  return $res
}

function parse_ES_ADD_ref() {
  local cname=$1
  local clink=$2
  local ref=$3

  # set value
  carg_set_param "$cname" $clink $ref

  return 0
}

function parse_ES_ADD_size() {
  local cname=$1
  local clink=$2
  local size=$3

  size="$(parse_size "$size")"
  if [ $? -ne 0 ]; then
    _attach_errormsg "Unrecognized size"
    return 1
  fi

  # set vanle
  carg_set_param "$cname" $clink $size

  return 0
}

function check_ES_LS() {
  return 0
}

function check_ES_ADD() {
  local cont_name
  local file_name
  local path=
  local is_internal=

  if [ -n "$_carg_ES_ADD_size_param" ]; then
    # size defined, so expecting file name of non-existing file:
    if [ -e "$_carg_ES_ADD_ref_param" ]; then
      _attach_errormsg "File exists ('$_carg_ES_ADD_ref_param'), not touching it!"
      return 1
    fi

    touch "$_carg_ES_ADD_ref_param" &> /dev/null
    if [ $? -ne 0 ]; then
      _attach_errormsg "Cannot create file: $_carg_ES_ADD_ref_param"
      return 1
    fi

    path=$(realpath "$_carg_ES_ADD_ref_param")
  else
    validate_cont_name "$_carg_ES_ADD_ref_param"
    cont_name=$?
    validate_path "$_carg_ES_ADD_ref_param"
    file_name=$?

    if [ $cont_name -ne 0 ] && [ $file_name -ne 0 ]; then
      _attach_errormsg "Illegal name"
      return 1
    fi

    path="${AWSTORE_DIR}/${_carg_ES_ADD_ref_param}.img"
    if [ $cont_name -eq 0 ] && [ -f "$path" ]; then
      # it's a container
      is_internal=true
    fi

    if [ $file_name -eq 0 ] && [ -f "${_carg_ES_ADD_ref_param}" ]; then
      # it's a file
      path="${_carg_ES_ADD_ref_param}"
      is_internal=false
    fi

    if [ -z "$is_internal" ]; then
      _attach_errormsg "Cannot find storage to attach (neither file nor container)"
      return 1
    fi
  fi

  # add special parameter
  carg_set_param "ES_ADD" "path" "${path}"

  return 0
}

function check_ES() {

  if [ -z $_carg_ES_MODE_param ]; then
    _attach_errormsg "Undefined extstore command"
    return 1
  fi

  return 0
}

function parse__RUN() {
  local res=0

  if [ ! -z $_carg__MODE_param ] && [ "$_carg__MODE_param" != "run" ]; then
    return 1
  fi

  _carg_chain_parse "--wait-w? name" "RUN"
  res=$?

  if [ -z $_carg__MODE_param ]; then
    carg_set_param "" "MODE" "run"
  fi

  return $res
}

function parse_RUN_name() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if ! validate_cont_name $name; then
    _attach_errormsg "Illegal name"
    return 1
  fi

  echo HIT "$cname" $clink $name
  if [ ! -d "$DB_DIR/$name" ]; then
    _attach_errormsg "Container does not exists"
    return 1
  fi

  carg_set_param "$cname" $clink $name

  return 0
}


function check_RUN() {
  return 0
}

_carg_COMMAND_arg_param=
function parse_COMMAND_arg() {
  local cname=$1
  local clink=$2
  local arg=$3

  _carg_COMMAND_arg_param="$_carg_COMMAND_arg_param $arg"
  # carg_set_param "$cname" $clink $arg
}

function check_COMMAND() {
  return 0
}

function parse_SYNC_path_local() {
  local cname=$1
  local clink=$2
  local path=$(realpath $3)

  if [ ! -f $path ] && [ ! -d $path ]; then
    _attach_errormsg "Provide correc file or directory path."
    return 1
  fi

  carg_set_param "$cname" $clink $path

  return 0
}

_carg_SYNC_path_remote_param=/usr/local/bin
function parse_SYNC_path_remote() {
  local cname=$1
  local clink=$2
  local path="$3"

  if ! validate_path "$path"; then
    _attach_errormsg "Incorrect path: $path"

    return 1
  fi

  carg_set_param "$cname" $clink $path
  return 0
}

# check main chain:
function check_() {

  if [ -n "$_carg__help_param" ] || [ -n "$_carg__help_flag" ]; then
    print_help
  elif [ -z $_carg__MODE_param ]; then
    echo "Wrong syntax"
    echo "    type '--help' for help"
    return 1
  fi

  return 0
}


function check_SYNC() {
  return 0
}



function main() {
  local res=
  # Prse arguments, if error accounted returns non-0 what terminates script (set -e)
  _carg_chain_parse "help? --help-h? MODE? CREATE? RUN?"

  case $_carg__MODE_param in
    create)
      echo "create: '${_carg_CREATE_device_flag}' '${_carg_CREATE_file_path_param}' ${_carg_CREATE_extr_size_param} ${_carg_CREATE_yesno_param} ${_carg_CREATE_kelner_param} ${_carg_CREATE_initramfs_param} ${_carg_CREATE_name_flag} ${parse_CREATE_cont_name_param}"
      #--device-d? dev_name? file_path extr_size? --imgboot-i yesno kelner? initramfs? --name-n? cont_name?" "create
    ;;
    run)
      echo "Run '${_carg_RUN_name_param}'"
    ;;
    command)
      echo "Command: " $_carg_COMMAND_arg_param
    ;;
    sync)
      echo "Sync: " $_carg_SYNC_path_local_param $_carg_SYNC_path_remote_param "$_carg_SYNC_reverse_flag"
    ;;
    console)
      echo "Console"
    ;;
    ls)
      echo "ls: $_carg_ls_full_flag"
      check_environment

      load_containersettings || res=$?
      op_list
    ;;
    stop)
      echo "Stop"
    ;;
    waitfor)
      echo "WaitRor"
    ;;
    es)
      case $_carg_ES_MODE_param in
        ls)
          echo "ls $_carg_es_ls_full_flag"
        ;;
        add)
          echo "add ${_carg_ES_ADD_ref_param} ${_carg_ES_ADD_size_param}: ${_carg_ES_ADD_path_param}"
          if [ -n "${_carg_ES_ADD_size_param}" ]; then
            prepare_usbstick "${_carg_ES_ADD_path_param}" ${_carg_ES_ADD_size_param}
          fi
        ;;
        eject)
          echo "Exect"
        ;;
      esac
    ;;
    init)
      exit_if_not_root

      echo "Initializing $SCRIPT_BASE database and storage"
      init

      exit $?
    ;;
  esac

  return 0
}

main
exit $?


function stop_machine() {
  /usr/bin/nc -U ${QEMU_MONITOR_UNIXSOCKET} -q 0 <<EOF
quit
EOF
  local ret=$?

  if [ $ret -eq 0 ]; then
    echo "VM ${_CONTAINER_NAME} sucessfully stopped."
  else
    echo "Failed to stop VM ${_CONTAINER_NAME}"
  fi

  return $ret
}

function insert_usbstick() {
  local PATH=$(realpath $1)

  local USB_STICK_CNT=$(/usr/bin/nc -U ${QEMU_MONITOR_UNIXSOCKET} -q 0 <<EOF | /usr/bin/grep 'Product QEMU USB MSD' | /usr/bin/wc -l
info usb
EOF
)

  local USB_DEV_ID="usbdrive$USB_STICK_CNT"

  /usr/bin/nc -U ${QEMU_MONITOR_UNIXSOCKET} -q 0 <<EOF
drive_add 0 if=none,id=${USB_DEV_ID},format=raw,file=${PATH}
device_add usb-storage,drive=${USB_DEV_ID},bus=usb-bus.0
EOF

  echo "USB mass storage device inserted: ${USB_DEV_ID}"

  #device_del usbdrive1
}

function remove_usbstick() {
# removing does not work!
  /usr/bin/nc -U $QEMU_MONITOR_UNIXSOCKET -q 0 <<EOF
drive_del usbdrive1
device_del usb-storage
EOF
}



function op_waitfor() {
  local ssh_key_path=${DB_DIR}/${_CONTAINER_NAME}/${SSH_DEF_PRIV_KEY_NAME}
  local WAIT_TIMEOUT=300             # Timeout (in seconds)
  local PING_INTERVAL=3
  SSH_OPTIONS="-o ConnectTimeout=3 -o BatchMode=yes"

  echo -n "Waiting for '${_CONTAINER_NAME}' to reach multi-user mode ."

  local ctime=$(date +%s)
  local wait_until=$((${ctime}+${WAIT_TIMEOUT}))

  while ! $(ssh -p ${SSH_GUEST_PORT} ${SSH_OPTIONS} -i ${ssh_key_path} root@localhost "[ $(rc-status -r) == "default" ]" 2> /dev/null); do
    sleep $PING_INTERVAL
    echo -n '.'

    if [ $(date +%s) -gt ${wait_until} ]; then
      echo ''
      echo "Container not accessible!"

      return 1
    fi
  done

  echo ''
  echo "'${_CONTAINER_NAME}' avaliable"

#  for (( sec=0; sec<=$WAIT_TIMEOUT; i+=$WAIT_INTERVAL )); do
#    if ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no -o BatchMode=yes "$SSH_USER@$VM_IP" "systemctl is-active multi-user.target" 2>/dev/null | grep -q "active"; then
#      echo "VM has reached multi-user mode!"
#      exit 0
#    fi
#    echo "Waiting for VM (attempt $((i/WAIT_INTERVAL+1)))..."
#    sleep $WAIT_INTERVAL
#  done

#  echo "Timed out waiting for VM to reach multi-user mode!"
  return 0
}

# determinate operation mode:
if [ -n "$_IMG_FILE" ]; then
  _MODE="image"
elif [ -n "$_CONTAINER_NAME" ]; then
  _MODE="container"
  # load settings
fi

case $_MODE in
  image)
    $_carg_CREATE_yesno_param && exit_if_not_root
    check_environment

    echo "Run image... ${parse_create_dev_name} ${_carg_CREATE_file_path_param} ${_carg_CREATE_kelner_param} ${_carg_CREATE_initramfs_param}"

    if [ ! -z ${_carg_CREATE_name_flag} ]; then
      echo "Creating continer: ${_carg_CREATE_cont_name_param}"

      CONT_FILE=${AWSTORE_DIR}/${_carg_CREATE_cont_name_param}.img
      if [ -f ${CONT_FILE} ]; then
        echo "Container '${_carg_CREATE_cont_name_param}' already exists."
        exit 4
      fi
    else
      # running tempolary container
      CONT_FILE=$(mktemp --tmpdir=${AWSTORE_DIR} --suffix=.img)
      _CONTAINER_NAME=$(basename ${CONT_FILE} ".img")
    fi

    prepare_mmc_imgfile ${_IMG_FILE} ${CONT_FILE}

    # set container's permissions for unprivileged user:
    chgrp libvirt ${CONT_FILE}
    chmod g+rw    ${CONT_FILE}

    mkdir -p ${DB_DIR}/${_CONTAINER_NAME}

    local kernel=
    local initrd=
    local cmdline=

    # root required
    if $_carg_CREATE_yesno_param; then
      # mount boot partition
      mount_boot $CONT_FILE

      kernel=${BOOT_MNT_DIR}/${_carg_CREATE_kelner_param}

      if [ ! -f "${kernel}" ]; then
        echo "Can not find kernel: ${kernel}"
        exit 44
      fi

      if [ -n "${_carg_CREATE_initramfs_param}" ]; then
        initrd=${BOOT_MNT_DIR}/${_carg_CREATE_initramfs_param}
        if [ ! -f "${initrd}" ]; then
          echo "Can not find initrd: ${initrd}"
          exit 44
        fi
      fi

      if [ -f ${BOOT_MNT_DIR}/cmdline.txt ]; then
        cmdline=${BOOT_MNT_DIR}/cmdline.txt
      fi
    else
      kernel=${_carg_CREATE_kelner_param}
      initrd=${_carg_CREATE_initramfs_param}
    fi

    # installation
    $RUN cp ${kernel} ${DB_DIR}/${_CONTAINER_NAME}/
    kernel=${DB_DIR}/${_CONTAINER_NAME}/$(basename ${kernel})

    if [ -n "${cmdline}" ]; then
      $RUN cp ${cmdline} ${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt
      cmdline=${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt
    fi

    if [ -n "${initrd}" ]; then
      $RUN cp ${initrd} $DB_DIR/$_CONTAINER_NAME/
      initrd=$DB_DIR/$_CONTAINER_NAME/$(basename ${initrd})
    fi

    cat <<EOF > $DB_DIR/${_CONTAINER_NAME}/config.txt
# file auto-generated
container $_CONTAINER_NAME
device    $_carg_CREATE_dev_name_param
kernel    ${kernel}
initramfs ${initrd}
imgboot   $_carg_CREATE_yesno_param

rootimg   $_carg_CREATE_file_path_param
cdate     $(date)
EOF

    $RUN chgrp libvirt -R ${DB_DIR}/${_CONTAINER_NAME}
    $RUN chmod g+w -R ${DB_DIR}/${_CONTAINER_NAME}

    # umount boot partition
    $_carg_CREATE_yesno_param umount_boot || true
  ;;

  container)
    check_environment

    _MACHINE=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^device'))
    _IMG_BOOT=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^imgboot'))
    _KERNEL=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^kernel'))
    _INITRAMFS=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^initramfs'))

    echo "Run container... $_MACHINE $_IMG_FILE $_KERNEL $_INITRAMFS"

    _KERNEL=$DB_DIR/${_CONTAINER_NAME}/$_KERNEL

    if [ -n "$_INITRAMFS" ]; then
      _INITRAMFS=$DB_DIR/${_CONTAINER_NAME}/$_INITRAMFS
    fi

    if [ -f "${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt" ]; then
      CMDLINE_FILE_PATH=${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt
    fi

    CONT_FILE=${AWSTORE_DIR}/${_CONTAINER_NAME}.img

    if [ ${_IMG_BOOT} -eq 1 ]; then
      mount_boot ${CONT_FILE}

      if ! $(cmp $BOOT_MNT_DIR/$(basename ${_KERNEL}) $_KERNEL); then
        # update kernel:
        $RUN cp $BOOT_MNT_DIR/$(basename ${_KERNEL}) ${_KERNEL}
      fi

      if [ -n "${_INITRAMFS}" ] && ! $(cmp $BOOT_MNT_DIR/$(basename ${_INITRAMFS}) ${_INITRAMFS}); then
        $RUN cp $BOOT_MNT_DIR/$(basename ${_INITRAMFS}) ${_INITRAMFS}
      fi

      if [ -n "${CMDLINE_FILE_PATH}" ] && ! $(cmp ${BOOT_MNT_DIR}/cmdline.txt ${CMDLINE_FILE_PATH}); then
        $RUN cp $BOOT_MNT_DIR/cmdline.txt ${CMDLINE_FILE_PATH}
      fi

      umount_boot
    fi
  ;;
  command)
    load_containersettings
    op_gcommand

    exit 0
  ;;
  sync)
    load_containersettings
    op_sync

    exit 0
  ;;
  enter)
    load_containersettings
    op_enter

    exit 0
  ;;
  stop)
    load_containersettings
    stop_machine && rm_lock_file && exit 0 || exit $?
  ;;
  waitfor)
    load_containersettings
    op_waitfor && exit 0 || exit $?
  ;;
  extstore)
    case $_EXTSTORAGE_MODE in
      ls)
        if [ ${_LIST_WITH_DETAILS} -eq 1 ]; then
          ls -l "${EXTSTORE_DIR}"
        else
          ls "${EXTSTORE_DIR}"
        fi
      ;;
      add)
        insert_usbstick "${_EXTSTORAGE_REF}"
      ;;
      eject)
        remove_usbstick
      ;;
    esac

    exit 0
  ;;

  *)
    # if undefined mode print help:
    print_help
    exit 2
  ;;
esac

# Test and run:

# At this point in the case of '--imgboot y' image boot partition is
# mounted and ${_KERNEL} and ${_INITRAMFS} (if defined) is a path to
# file within mounted boot partition.
# Therefore below code tests for kernel and initramfs existsnce
# regardless of '--imgboot' option.



M_CPU=${devices_cpu[${_carg_CREATE_dev_name_param}]}
M_DTB=${devices_dtb[${_carg_CREATE_dev_name_param}]}


DTB_FILE=${DTB_LIB}/${M_DTB}

if [ ! -f "${DTB_FILE}" ]; then
  echo "DTB file has not been found: ${DTB_FILE}"
  exit 3
fi

#   -chardev socket,id=com0,path=/tmp/builder1.sock,server=on,wait=off \
# mount /dev/loop1p2 /mnt/dir
# cd /mnt/dir
# rm ./systemd/system/multi-user.target.wants/userconfig.service
#

# PCI required:
#   -virtfs local,path=./share,mount_tag=host0,security_model=passthrough,id=host0 \

# looks like system does not create /dev/ttyAMA0 device,
# as a result only boot messages are print, can't login
# All (Ethernet and mass storage) USB devices running at USB 1.1 speed
# slow, but works well and no rush
function run() {
  KERNEL_LINE="-kernel ${_KERNEL}"

  # add initrd if its used
  if [ -n "${_INITRAMFS}" ]; then
    KERNEL_LINE="${KERNEL_LINE} -initrd ${_INITRAMFS}"
  fi

  if [ -n "${CMDLINE_FILE_PATH}" ]; then
    KERNEL_PARAMS=$(tail -n 1 "${CMDLINE_FILE_PATH}")
  else
    # default kernel parameters
    KERNEL_PARAMS="console=tty1 console=ttyAMA0 root=/dev/mmcblk0p2 rw"
    # console=ttyAMA1

    # Set parameters
    if [ ${_NO_PART_TABLE_MODE} -eq 0 ]; then
      KERNEL_PARAMS="${KERNEL_PARAMS} root=/dev/mmcblk0p2 rw"
    else
      KERNEL_PARAMS="${KERNEL_PARAMS} modules=loop,squashfs,sd-mod,usb-storage"
    fi
  fi

  if [ -e ${LOCK_FILE} ]; then
    QEMU_ID=$(head -n 1 ${LOCK_FILE})

    if ! kill -0 "$QEMU_ID" 2>/dev/null; then
      echo "Lock file found, but no process"
      echo "Removing: ${LOCK_FILE}"
      echo "This indicates that program might have crash before."

      rm "${LOCK_FILE}"
    else
      echo "Lock for container: "
      tail -n 1 ${LOCK_FILE}
      echo "Is it already running?"
      exit 5
    fi
  fi

  # add PID and container name
  echo $$ > ${LOCK_FILE}
  echo ${_CONTAINER_NAME} >> ${LOCK_FILE}

  #  -cpu ${M_CPU} -m 1024

  EXTR_OPT=""
  if [ ${_OPTION_DETACH} -eq 1 ]; then
    EXTR_OPT="${EXTR_OPT} -daemonize"
  fi

  $RUN /usr/bin/qemu-system-aarch64 \
    -M ${_MACHINE} \
    -monitor unix:$QEMU_MONITOR_UNIXSOCKET,server,nowait \
    -serial pty \
    ${KERNEL_LINE} -append "${KERNEL_PARAMS}" \
    -drive id=sysdrive,if=none,format=raw,file=${CONT_FILE} \
    -device sd-card,drive=sysdrive \
    -usb \
    -device usb-kbd,bus=usb-bus.0 \
    -netdev user,id=net0,hostfwd=tcp::${SSH_GUEST_PORT}-:22 \
    -device usb-net,bus=usb-bus.0,netdev=net0 \
    -dtb ${DTB_FILE} \
    -rtc base=localtime \
    ${EXTR_OPT} -name "$_MACHINE emulator"

    # lock file is removed by 'stop' command
    #rm ${LOCK_FILE}

    # Requiers PCI:
    #     -virtfs local,id=sharedFolder,path=/tmp/aa,security_model=passthrough,mount_tag=hostshare \
    #     -drive id=imgout0,if=none,format=raw,file="${EXTSTORE_DIR}/${_CONTAINER_NAME}-01.img" \
    #      -device usb-storage,bus=usb-bus.0,drive=imgout0 \
}

run

if [ "${_MODE}" == "image" ] && [ "${_carg_CREATE_name_flag}" != "0" ]; then
  $RUN rm "${CONT_FILE}"
  $RUN rm -rf ${DB_DIR}/${_CONTAINER_NAME}
fi

exit 0
