#!/bin/bash

[ -n "$DEBUG" ] && [[ $(echo "$DEBUG" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        set -xe || set -e


_carg_dbg() {
  echo "DEBUG: $*"
}

_carg_dbg_sink() {
  return 0
}

_errors=
function _attach_errormsg() {
  for msg in "$@"; do
    _errors="$_errors
$msg"
  done
}

_DBG_MSG=_carg_dbg_sink

function first_arg() {
  printf '%s' "$1"
}

function second_arg() {
  printf '%s' $2
}

function last_args() {
  [ -n "$1" ] && shift

  if [ -z $1 ]; then
    return
  fi

  printf '%s' "$1"
  shift
  for a in "$@"; do
    printf ' %s' "$a"
  done
}


function carg_set_param() {
  local cname=$1
  local clink=$2
  local value=$3

  if [ -z ${value} ]; then
    # no thing to set
    return 0
  fi

  # declare if value not defined, defined value is a default value
  local param_name="_carg_${cname}_${clink}_param"
  if [ -z ${!param_name} ]; then
    declare -gr "${param_name}=${value}"
  else
    eval "${param_name}=${value}"
  fi
}

function carg_isparam_set() {
  local cname=$1
  local clink=$2
  local var="_carg_${cname}_${clink}_param"

  [ -n "${!var}" ]
  return $?
}

# Return value:
#     0 - argument has been parsed successfully
#     1 - argument can't be interpreted
#
# If parameter is accepted, it must be registered with:
#   carg_set_param function
function parse___autoparam() {
  local cname=$1
  local clink=$2
  local value=$3

  if [ $clink == $value ]; then
    carg_set_param "$cname" $clink 1
    return 0
  fi

  return 1
}


# prepare arguments:
# ARGS exported by caller script
CARG=

function _carg_chain_parse() {
  local chain=$1
  local name=$2
  local arg_type=
  declare -A flag_conv
  declare -A flag_subch_sidx
  declare -A chain_qant
  declare -A chain_param_fn
  local cflag=
  local clflag=
  local cflag_dist=
  local qant=
  local res=0
  local tmp=

  local chain_arr
  read -a chain_arr <<< "$chain"

  local link=
  local link_idx=0
  # First chain pass: scann for flags and named parameters:
  $_DBG_MSG "Loading chain: _$name"
  $_DBG_MSG "    $chain"


  for link_idx in ${!chain_arr[@]}; do
    link=${chain_arr[$link_idx]}

    tmp=${link:0,-1}
    if [ "$tmp" == "?" ] || [ "$tmp" == "*" ]; then
      chain_qant[$link_idx]=$tmp
      link=${link:0:-1}
    else
      chain_qant[$link_idx]=
    fi

    tmp=${link:0,-2}
    if [ ${link:0:1} == '-' ]; then
      if [[ ! $tmp =~ ^\-[0-9A-Za-z]$ ]]; then
        echo "Internal error: "
        echo "    Illegal syntax (flag '$link' in '$name: $chain')"
        exit 52
      fi

      cflag=${tmp:1}

      tmp=${link:0:-2}
      if [ -n "$tmp" ]; then
        if [[ ! $tmp =~ ^\-\-[0-9A-Za-z]{1,128}$ ]]; then
          echo "Internal error: "
          echo "    Illegal syntax (flag '$link' in '$name: $chain')"
          exit 51
        fi

        clflag=${tmp:2}
        flag_conv[$cflag]=$clflag
        flag_conv[$clflag]=$cflag
      else
        flag_conv[$cflag]=$cflag
        clflag=$cflag
      fi

      flag_subch_sidx[$cflag]=$(($link_idx+1))
      link="-$cflag"

      $_DBG_MSG "      ($link_idx) adding flag: $clflag($cflag)${chain_qant[$link_idx]}, assoc. var.: _carg_${name}_${clflag}_flag"

      # it's a flag, 'param function' does not apply here:
      chain_param_fn[$link_idx]=""
    else # parameter
      if declare -F parse_${name}_${link} > /dev/null; then
        chain_param_fn[$link_idx]="parse_${name}_${link}"
      else
        chain_param_fn[$link_idx]="parse___autoparam"
      fi

      $_DBG_MSG "      ($link_idx) adding param. fn.: ${chain_param_fn[$link_idx]}${chain_qant[$link_idx]} expecting: 'parse_${name}_${link}' storing value into: '_carg_${name}_${link}_param'"
    fi

    # make correction:
    chain_arr[$link_idx]=$link
  done


  link_idx=0
  link_cnt=${#chain_arr[@]}

  local carg_loc=
  local flag_as_param=
  local pass_flag_to_next_chain=false
  local pass_flag_to_mcast_link=false
  local tailing_cnt=
  local arg_consumed_but_failed=false

  #_CARG_PARSER_ARG_REWINDED=false
  #if [ -z "$CARG" ]; then
  #    # read and rewind arguments
  #    CARG=$(first_arg ${ARGS})
  #    ARGS=$(last_args ${ARGS})
  #fi

  $_DBG_MSG "Parsing arguments: "

  while true; do

    if [ -z "$CARG" ]; then
      # read and rewind arguments
      CARG=$(first_arg ${ARGS})
      ARGS=$(last_args ${ARGS})

      if [ -z "$CARG" ]; then
        # quantifier is not '?' nor '*'
        $_DBG_MSG "      All arguments exploited, exiting _$name chain"

        if [ $res -ne 0 ] && [ "${link^^}" == "${link}" ]; then
          $_DBG_MSG "      Chain parser '${name}_${link} exited with an error"
          arg_consumed_but_failed=true
        fi

        break
      fi

      $_DBG_MSG "    Loading: $CARG"
    fi
    carg_loc=$CARG

    flag_as_param=$($pass_flag_to_next_chain || $pass_flag_to_mcast_link && echo true || echo false)
    if ! $flag_as_param && [[ "${CARG:0:1}" == "-" ]]; then
      # if long form
      if [[ "${CARG:0:2}" == "--" ]]; then
        clflag=${CARG:2}
        tmp=${flag_conv[$clflag]}
        cflag=$tmp
      else
        cflag=${CARG:1}
        tmp=${flag_conv[$cflag]}
        clflag=$tmp
      fi

      if [ -z "$tmp" ]; then
        $_DBG_MSG "      unidentified flag, mark 'flag_is_flag=false' to keep matching in other chains"
        # Flag does not exists in a current chain, but it might be in other one

        # flag_is_flag=false
        pass_flag_to_next_chain=true
        link_idx=$(($link_idx + 1))
        continue
        #break
      fi

      cflag_dist=0
      link_idx=${flag_subch_sidx[$cflag]}

      tmp=$(($link_idx - 1))
      $_DBG_MSG "      identified as a flag: $clflag($cflag) ${chain_qant[$tmp]}"
      # flag exits, mark, and jump to flag specific index
      tmp="_carg_${name}_${clflag}_flag"
      if [ ! -z ${!tmp} ]; then
        echo "Repeated flag: --$clflag (-cflag)"
        exit 3
      fi

      declare -g "_carg_${name}_${clflag}_flag=1"

      CARG=
      continue
    else # 'CARG' is a parameter OR an EMPTY string
      if [ $link_idx -ge $link_cnt ]; then
        # last element exceeded
        $_DBG_MSG "      End of chain: _$name"

        break
      fi

      link=${chain_arr[$link_idx]}
      qant=${chain_qant[$link_idx]}

      $_DBG_MSG "    Parsing argument against: ${name}:${link}${qant}"

      # if param is not defined, arg. is a flag
      if [ -z ${chain_param_fn[$link_idx]} ]; then
        if [ -z $qant ]; then
          tmp=flag_conv[${link}]
          echo "Expecting '--$tmp (-$link)' but '$CARG' encountered"
          exit 2
        fi

        $_DBG_MSG "    Flag in chain encountered: ${flag_conv[$link]}($link)$qant, checking arg. with next chain link"
        # next try
        link_idx=$(($link_idx + 1))
        continue
      fi

      $_DBG_MSG "    Testing arg. against parameter: ${link}${qant}"

      if [ -n "$cflag_dist" ]; then
        cflag_dist=$(($cflag_dist + 1))
      fi

      if ${pass_flag_to_next_chain} && [[ "${link^^}" != "${link}" ]]; then
        $_DBG_MSG "Link '_$link' is not a CHAIN link, continue parsing within parent chain"
        break
      fi

      if ${pass_flag_to_mcast_link} && [ "${qant}" != "*" ]; then
        $_DBG_MSG "Link is not 'match many' quantified, continue parsing within parent chain"
        break
      fi

      $_DBG_MSG "      Calling: ${chain_param_fn[$link_idx]} \"${name}\" ${link} $carg_loc $cflag $cflag_dist"
      tailing_cnt=${#ARGS}

      ${chain_param_fn[$link_idx]} "${name}" ${link} $carg_loc $cflag $cflag_dist && res=0 || res=$?

      if [ $res -eq 0 ]; then

        if ${flag_is_flag} && ! $(carg_isparam_set "${name}" ${link}); then
          $_DBG_MSG "No parameter has been set by parser, it is legal for chains (and multicast parsers)"
        fi

        tmp=_carg_${name}_${link}_param
        if ${pass_flag_to_next_chain}; then
          $_DBG_MSG "      Flag as param. '$carg_loc' has been accepted by parser '$tmp'"
          pass_flag_to_next_chain=false
        else
          $_DBG_MSG "      Param variable '$tmp' has been set with value: '${!tmp}'"
        fi

        # next try
        if [ "$qant" != "*" ]; then
          $_DBG_MSG "     Trying next link"
          # keep 'pass_flag_to_mcast_link' for next maches
          link_idx=$(($link_idx + 1))
        else
          $_DBG_MSG "     mcast quantifier, match against '${name}:${link}', including flags"
          pass_flag_to_mcast_link=true
        fi

        # if we quit from chain:
        # if [ -n "${link}" ] &&
        if [[ "${link^^}" != "${link}" ]]; then
          CARG=
        else
          $_DBG_MSG "     Exited from chain: '_${link}'. Chain should always rewind argument to the one that has not been recognized"
        fi

        continue
      fi

      if [ -z $qant ]; then
        echo "Missing required parameter: $name:$link"
        # exit and skip checker function
        return 1
      fi

      # Was argument rewind?
      if [ $tailing_cnt -ne ${#ARGS} ]; then
        # the argument was eaten by link, but it has not been validated sucesfully by parser
        # indicating wrong syntax
        arg_consumed_but_failed=true
        break
      fi

      $_DBG_MSG "      Param have not meet parser conditions, continue maching with a next link"

      if [ "$qant" == "*" ]; then
        $_DBG_MSG "     mcast not mached, arg.: ${carg_loc}"
        # disable 'pass_flag_to_mcast_link'
        pass_flag_to_mcast_link=false
      fi

      link_idx=$(($link_idx + 1))
    fi
  done

  if ! declare -F check_$name > /dev/null; then
    echo "Internal error: "
    echo "    Function 'check_$name' not defined!"
    exit 44
  fi

  $_DBG_MSG "Calling checker: check_$name"
  check_$name && tmp=0 || tmp=$?

  if ${arg_consumed_but_failed}; then
    tmp=1
  fi

  # if main chain and errors found
  if [ -z $name ]; then
    if [ $tmp -ne 0 ]; then
      echo "$_errors"
    fi

    if [ -n "$CARG" ] || [ ${#ARGS} -ne 0 ]; then
      echo "Unrecognized argument(s): $CARG ${ARGS[@]}"
      tmp=1
    fi
  fi

  return $tmp
}
