#!/bin/sh

[ -n "$PRETEND" ] && [[ $(echo "$PRETEND" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        RUN="echo" || RUN=

[ -n "$DEBUG" ] && [[ $(echo "$DEBUG" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        set -xe || set -e


function include_all() {
  readonly SCRIPT_PATH=$1
  readonly SCRIPT_BASE=$(basename $1)
  readonly SCRIPT_DIR=$(dirname $1)

  for script in $(ls ${SCRIPT_DIR}/${SCRIPT_BASE}-* 2>/dev/null); do
    if [ -x $script ]; then
      source $script
    fi
  done
}

export RUN
export DEBUG

export ARGS="$@"
include_all $0


# shellcheck disable=SC2112
function print_help() {
    cat <<EOF
Usage:
Creating container:
$SCRIPT_BASE --device|-d [raspi3b] <img file> [+SIZE] --imgboot|-i y|n <kernel> <initramfs> --cmdline|-C <path|cmdl> --name|-n <name>

  --device|-d      - Model of the emulated device (default: '${_carg_CREATE_dev_name_param}').
  <img file>       - Path to image file to be mounted as 'mmcblk0'.
  --imgboot|-i y|n - If 'y' load <kernel> and <initramfs> from a boot
                     partition of the image file.
                     If 'n' load <kernel> and <initramfs> from file.
                     <kernel>    - Path to kernel, if '-i y' path within
                                   boot partition of the image file.
                                   If '-i n' path to kernel file that is
                                   located at host.
                     <initramfs> - Path to initramfs, if '-i y' path within
                                   boot partition of the image file.
                                   If '-i n' path to initramfs file that is
                                   located at host.
                     Initramfs is optional, if not provided emulated system
                     will boot with just kernel image. It means that kernel
                     must have all modules to mount root fs as well as to
                     access necessary devices such as disk controller.

                     Also, <kernel> path might be skiped, in this case default
                     '${_KERNEL}' is loaded from boot image file partition
                     (if '-i y'), or current directory of a local file system
                     (if '-i n'). In this case initramfs can't be used.

  --cmdline|-C     - Kernel command line line, or file path. If VM is loaded
                     with '-i y' (boot from image's '/boot' partition) $SCRIPT_BASE
                     uses 'cmdline.txt' that is found in an image.
                     This parameter can be used with '-i n' when image is not
                     examined to pass kernel command line parameters.
                     Note, with '-i n' kernel and optionally initramfs must be
                     provided to VM as an external files.
                     If '--cmdline' is used in combination with '-i y', original
                     'cmdline.txt' that is normally stored at boot partition is not
                     loaded by $SCRIPT_BASE, instead provided command line with
                     '--cmdline' is applied.
                     '--cmdline' argument can be path to 'cmdline.txt' file, or an
                     actual kernel command line.

  --name|-n        - Create named container, in option '-n' is followed by
                     <name> container with a given name is created.
                     If only option '-n' is provided container with random name
                     is created, name of the container is displayed upon launch.

                     If option '-n' is not provided then temporary container is
                     created - it will be removed after machine is stopped.

Launching container:
$SCRIPT_BASE <container name> [--wait|-w]
  This will launch container that has been created from an image.
  --wait|-w    wait until guest os is up.

Guest interaction:
$SCRIPT_BASE command <command to be exiecuted in guest>
  This will launch provided command (over SSH) in VM.

$SCRIPT_BASE sync <host source dir> [<guest target dir>] --reverse|-r
  This will synchronize local file or directory with a location on guest
  system (over SSH). <guest target dir> can be skipped, if so default location
  is '/usr/local/bin'.
  --reverse|-r    Synchronize guest location with a host local directory (reversed
                  order)

$SCRIPT_BASE enter|console
  Enter (via ssh) VM guest console.

$SCRIPT_BASE stop
  Shutdown running machine.

$SCRIPT_BASE waitfor
  Wait until machine is responding.

Listing containers:
$SCRIPT_BASE ls --full|-f
  ls - list all defined containers

Attachable (extstore) image operations:
$SCRIPT_BASE extstore [ls --full|-f] | [add <name|path> SIZE] | [eject]
  Container can have virtually attached external ("USB stick") storage.

  extstore ls  - list attachable images
    --full|-f  - list attachable images with details

  extstore add - add 'external' storage to machine, the storage will be
                 available as USB stick. Storage can be identified by a path,
                 or name. If identified by path, '$SCRIPT_BASE' is expecting
                 a file name. Indicated file will be attached to machine as a
                 storage device.
                 If name provided, '$SCRIPT_BASE' will search for an
                 attachable image in its internal storage system.

                 If storage exists, it will be attached to the machine.
                 In order to create storage, non existing image name or path
                 must be provided followed by a size. '$SCRIPT_BASE' will
                 create storage of a given size and attach it to the machine.

                 New storage is automatically initiated with zeros.
                 Default SIZE unit is MiB, SIZE can be postfixed by MiB, MB,
                 GiB, GB e.g.: 2GB

Initialization:
$SCRIPT_BASE init
  Create storage backends, databases etc. for $SCRIPT_BASE

EOF
}


# sd-card size must be of power 2, e.g.:
# 512MiB, 1GiB, 2GiB, 4GiB ...
# Append extra 'zeros' to an end of an
# image file to ensure that its size is
# exactly 2^<power> bites.
function prepare_mmc_imgfile() {
  local IMAGE_PATH="$1"
  local CACHE_FILE="$2"

  if [ ! -f "$CACHE_FILE" ] || [ ! -s "$CACHE_FILE" ] ; then
    # if file does not exists, or is a zero size copy image
    $RUN cp "$IMAGE_PATH" $CACHE_FILE
  fi
  # else, if file already exists veriry size

  CUR_SIZE=$(first_arg $(du -sb $IMAGE_PATH))

  POW=$(( 256*1024*1024 ))

  while [ $POW -lt $CUR_SIZE ]; do
    POW=$(($POW*2))
    #echo $POW
  done

  REM_SIZE_TOPOW=$(($POW - $CUR_SIZE))

  # if zero file is of a proper size already

  if [ $REM_SIZE_TOPOW -ne 0 ]; then
    #echo "Appending file with extra 'zeros' to reach size that is a power of 256 MiB (requirment for SD cards)"
    #echo "Appending by: $REM_SIZE_TOPOW bytes"
    #echo "Final size: $(($REM_SIZE_TOPOW + $CUR_SIZE)) bytes"

    # make file size to be multiple of MB:
    TAIL=$(( ($REM_SIZE_TOPOW % $ONE_MIB) ))

    # init is in bytes
    if [ $TAIL -ne 0 ]; then
      $RUN dd bs=1 seek=$CUR_SIZE if=/dev/zero of=$CACHE_FILE count=$TAIL
    fi

    # change units to MiB
    CUR_SIZE=$(( ($CUR_SIZE + $TAIL) / $ONE_MIB ))
    TAIL=$(($REM_SIZE_TOPOW / $ONE_MIB))

    if [ $TAIL -ne 0 ]; then
      $RUN dd bs=$ONE_MIB seek=$CUR_SIZE if=/dev/zero of=$CACHE_FILE count=$TAIL
    fi
  fi
}

function prepare_usbstick() {
  local PATH=$1
  local SIZE_MB=$2

  $RUN /usr/bin/dd bs=$ONE_MIB count=${SIZE_MB} if="/dev/zero" of="${PATH}"
}



# Command line parsing functions:

function set_flag_imgboot() {
  if [ -n "$2" ] && [ "yes_no" == "$2" ]; then
    _IMG_BOOT=$1
  fi
}


_RSYNC_LOCAL=
_RSYNC_REMOTE=/usr/local/bin
_RSYNC_REVERSE=0



function parse_sync_path1() {
  # actually accept anything
  if [ -n "${1}" ]; then
    _RSYNC_LOCAL=$1
    return 1
  fi

  return 0
}

function parse_SYNC_path2() {
  # accept anything
  if [ -n "${1}" ]; then
    _RSYNC_REMOTE=$1
    return 1
  fi

  return 0
}

function parse_reverse_sync() {
  if [ "$1" == "-r" ] || [ "$1" == "--reverse" ]; then
    _RSYNC_REVERSE=1
    # read
    return 1
  fi

  return 0
}

function set_sync() {
  # arg (param, flag) or chain (root chain, param chain, flag chain)

  # skip arg. setters
  if [ $# -eq 2 ]; then
    # accept
    return 1
  fi

  # set flag
  if [ $# -eq 1 ]; then
    # per parameter setter call
    parse_reverse_sync "${1}"
    retval=$?
    return ${retval}
  fi

  # final setter call:
  local l_loc
  local r_loc

  l_loc=$(realpath ${_RSYNC_LOCAL})
  r_loc="${_RSYNC_REMOTE}"

  if [ ! -e ${l_loc} ]; then
    echo "File or directory does not exists!"

    exit 3
  fi
}

function flag_opt() {
  if [ "$1" == "-f" ] || [ "$1" == "--full" ]; then
    _LIST_WITH_DETAILS=1
    return 1
  fi

  return 0
}

# if something default define it:
_EXTSTORAGE_MODE=add
_EXTSTORAGE_REF=
_EXTSTORAGE_REF_ISINTERNAL=
_EXTSTORAGE_SIZE=

function parse_size() {
  local input="$1"
  local number
  local unit
  local result
  local size

  # Use regular expression to match the number and unit (MB, GB, MiB, GiB)
  if [[ "$input" =~ ^([0-9]+(\.[0-9]+)?)\ ?(m|g|M|G|MB|GB|MiB|GiB)$ ]]; then
    number="${BASH_REMATCH[1]}"
    unit="${BASH_REMATCH[3]}"

    case "$unit" in
      m|M|MB)
        result=$(echo "scale=2; $number * 0.953674" | bc)
      ;;
      g|G|GB)
        result=$(echo "scale=2; $number * 953.674" | bc)
      ;;
      MiB)
        result="$number"
      ;;
      GiB)
        result=$(echo "scale=2; $number * 1024" | bc)
      ;;
    esac

    # Round up to the nearest integer using awk
    size=$(echo "$result" | awk '{print ($1 == int($1)) ? $1 : int($1)+1}')
    echo "$size"

    return 0
    #echo "Invalid input. Please provide a number followed by MB, GB, MiB, or GiB."
  fi

  return 1
}



setter_fn=
param_chain=




function parse__MODE() {
  local cname=$1
  local clink=$2
  local cmd=$3
  local res=0

  case $cmd in
    command|exec)
      CARG=
      cmd="command"
      _carg_chain_parse "arg*" "COMMAND"
      res=$?
    ;;
    sync)
      CARG=
      _carg_chain_parse "--reverse-r? path_local path_remote?" "SYNC"
      res=$?
    ;;
    enter|console)
      # no parameters
      CARG=
      cmd="console"
    ;;
    stop|waitfor|init)
      # no argumans for these options
      CARG=
    ;;
    ls)
      CARG=
      _carg_chain_parse "--full-f?" $cmd
      res=$?
    ;;
    extstore|es)
      cmd="es"
      CARG=
      _carg_chain_parse "MODE" "ES"
      res=$?
    ;;
    create|run)
      CARG=
      # chain to be called later
    ;;
    *)
      # cmd to be defined later from context
      # it might be run or create
      cmd=
      res=1
    ;;
  esac

  # set value
  carg_set_param "$cname" $clink $cmd

#  [ -n "$cmd" ]
  return $res
}


function parse__CREATE() {
  local res=0

  if [ ! -z $_carg__MODE_param ] && [ "$_carg__MODE_param" != "create" ]; then
    return 1
  fi

  _carg_chain_parse "--device-d? dev_name? file_path extr_size? --imgboot-i yesno kelner? initramfs? --cmdline-C? cmdline? --name-n? cont_name?" "CREATE"
  res=$?

  if [ $res -eq 0 ] && [ -z $_carg__MODE_param ]; then
    carg_set_param "" "MODE" "create"
  fi

  return $res
}

_carg_CREATE_dev_name_param=raspi3b
function parse_CREATE_dev_name() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ "$prev_flag" != "d" ] || [ "$prev_flag_dist" != "1" ]; then
    return 1
  fi

  if [[ ! "$name" =~ ^([a-zA-Z0-9\._-]){1,128}$ ]]; then
    echo "Illegal machine (device) name"
    exit 3
  fi

  local machine=$(qemu-system-aarch64 -machine help | grep "^${name}[[:space:]].*")

  if [ -z "$machine" ]; then
    echo "Machine (device) has not been found: $name"
    exit 3
  fi

  # echo "Loading: $machine"
  carg_set_param "$cname" $clink $(first_arg $machine)

  return 0
}

function parse_CREATE_file_path() {
  local cname=$1
  local clink=$2
  local path=$3

  if [ -n "$path" ]; then
    path=$(realpath $path)
    if [ -f $path ]; then
      # set value
      carg_set_param "$cname" $clink $path
      return 0
    fi

    if [ -z $__carg__MODE_param ]; then
      # this will force to try next chain
      return 1
    else
      echo "Provide path to an existing file"
      exit 3
    fi
  fi

  return 1
}

function parse_CREATE_extr_size() {
  local cname=$1
  local clink=$2
  local size="$3"
  local res=

  if [ "${size:0:1}" != '+' ]; then
    return 1
  fi

  size="${size:1}"
  size="$(parse_size "$size")"
  res=$?

  if [ $res -ne 0 ]; then
    echo "Incorrect size format"
    exit 22
  fi

  carg_set_param "$cname" $clink "$size"
  return 0
}

function parse_CREATE_yesno() {
  local cname=$1
  local clink=$2
  local value=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'i' ] || [ $prev_flag_dist -ne 1 ]; then
    return 1
  fi

  if [[ $(echo "$value" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] ; then
    carg_set_param "$cname" $clink true
  elif [[ $(echo "$value" | tr '[:upper:]' '[:lower:]') =~ ^n|no|0|off$ ]] ; then
    carg_set_param "$cname" $clink false
  else
    echo "Correct option is one of: yes, y, on, 1 or no, n, 0, off"
    exit 3
  fi

  return 0
}

# default kernel:
_carg_CREATE_kelner_param=vmlinuz
function parse_CREATE_kelner() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'i' ] || [ $prev_flag_dist -ne 2 ]; then
    return 1
  fi

  if [[ ! "$name" =~ ^([a-zA-Z0-9\._/-]){1,128}$ ]]; then
    echo "Illegal kernel name"
    exit 3
  fi

  carg_set_param "$cname" $clink "$name"
  return 0
}

_carg_CREATE_initramfs_param=
function parse_CREATE_initramfs() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'i' ] || [ $prev_flag_dist -ne 3 ]; then
    return 1
  fi

  if [[ ! "$name" =~ ^([a-zA-Z0-9\._/-]){1,128}$ ]]; then
    echo "Illegal initramfs name"
    exit 3
  fi

  # carg_set_param "$cname" $clink "$name"
  _carg_CREATE_initramfs_param="$name"
  return 0
}

function parse_CREATE_cmdline() {
  local cname=$1
  local clink=$2
  local cmdl=$3
  local prev_flag=$4
  local prev_flag_dist=$5
  local cmdline=
  local filesize=

  echo "$cname $clink $cmdl $prev_flag $prev_flag_dist"

  if [ $prev_flag != 'C' ] || [ $prev_flag_dist -ne 1 ]; then
    return 1
  fi

  if $(validate_path "${cmdl}") && [ -f "${cmdl}" ]; then
    filesize=$(stat -c%s "$cmdl")

    # assuming file can have a lot of comments
    # this treshold will not allow to load e.g. initramfs
    # (in the case of mistake)
    if (( filesize > 4096 )); then
      _attach_errormsg "File too large, is 'cmdline.txt'?"
        return 1
    fi

    cmdline=$(tail -n 1 "${cmdl}")
  else
    cmdline="${cmdl}"
  fi

  if ! $(validate_cmdline "${cmdl}"); then
    _attach_errormsg "Provided 'command line' does not look legitimate."
    return 2
  fi

  carg_set_param "$cname" $clink "${cmdline}"

  return 0
}

function parse_CREATE_cont_name() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if [ $prev_flag != 'n' ] || [ $prev_flag_dist -ne 1 ]; then
    return 1
  fi

  if ! validate_cont_name "$name"; then
    echo "Illegal name"
    exit 3
  fi

  carg_set_param "$cname" $clink $name

  return 0
}


function check_CREATE() {
  local err_enc=false

  if [ -z $_carg_CREATE_file_path_param ]; then
    _attach_errormsg "Provide image path" "create"
    err_enc=true
  fi

  if [ -z $_carg_CREATE_yesno_param ]; then
    _attach_errormsg "Define '--imgboot': yes|no" "create"
    err_enc=true
  fi

  if $err_enc; then
    return 1
  fi

  if ! ${_carg_CREATE_yesno_param}; then
    if [ ! -f "${_carg_CREATE_kelner_param}" ]; then
      if [ -e "${_carg_CREATE_kelner_param}" ]; then
        _attach_errormsg "Path '${_carg_CREATE_kelner_param}' should point to (kernel) file"
      else
        _attach_errormsg "Can not find kernel: '${_carg_CREATE_kelner_param}'"
      fi
      err_enc=true
    fi

    # set realpath
    _carg_CREATE_kelner_param=$(realpath $_carg_CREATE_kelner_param)

    if [ -n "${_carg_CREATE_initramfs_param}" ]; then
      if [ ! -f "${_carg_CREATE_initramfs_param}" ]; then
        if [ -e "${_carg_CREATE_initramfs_param}" ]; then
          _attach_errormsg "Path '${_carg_CREATE_initramfs_param}' should point to (initramfs) file"
        else
          _attach_errormsg "Can not find initramfs: '${_carg_CREATE_initramfs_param}'"
        fi
        err_enc=true
      fi

      _carg_CREATE_initramfs_param=$(realpath $_carg_CREATE_initramfs_param)
    fi
  fi

  if $err_enc; then
    return 1
  fi

  # Create random name if user did not assign
  if [ "${_carg_CREATE_name_flag}" == "1" ] && [ -z ${parse_CREATE_cont_name_param} ]; then
    _carg_CREATE_cont_name_param=$(get_random_name)
    echo "Random name assigned: ${_carg_CREATE_cont_name_param}"
  fi

  return 0
}

function check_ls() {
  return 0
}

function parse_ES_MODE() {
  local cname=$1
  local clink=$2
  local subcmd=$3
  local res=0

  case $subcmd in
    ls)
      _carg_chain_parse "ls --full-f?" "${cname}_LS"
      res=$?
    ;;
    add)
      _carg_chain_parse "add ref size?" "${cname}_ADD"
      res=$?
    ;;
    eject)
      # no parameters
      CARG=
    ;;
    *)
      echo "Unknown option: $subcmd"
    ;;
  esac

  # set value
  carg_set_param "$cname" $clink $subcmd

  return $res
}

function parse_ES_ADD_ref() {
  local cname=$1
  local clink=$2
  local ref=$3

  # set value
  carg_set_param "$cname" $clink $ref

  return 0
}

function parse_ES_ADD_size() {
  local cname=$1
  local clink=$2
  local size=$3

  size="$(parse_size "$size")"
  if [ $? -ne 0 ]; then
    _attach_errormsg "Unrecognized size"
    return 1
  fi

  # set vanle
  carg_set_param "$cname" $clink $size

  return 0
}

function check_ES_LS() {
  return 0
}

function check_ES_ADD() {
  local cont_name
  local file_name
  local path=
  local is_internal=

  if [ -n "$_carg_ES_ADD_size_param" ]; then
    # size defined, so expecting file name of non-existing file:
    if [ -e "$_carg_ES_ADD_ref_param" ]; then
      _attach_errormsg "File exists ('$_carg_ES_ADD_ref_param'), not touching it!"
      return 1
    fi

    touch "$_carg_ES_ADD_ref_param" &> /dev/null
    if [ $? -ne 0 ]; then
      _attach_errormsg "Cannot create file: $_carg_ES_ADD_ref_param"
      return 1
    fi

    path=$(realpath "$_carg_ES_ADD_ref_param")
  else
    validate_cont_name "$_carg_ES_ADD_ref_param"
    cont_name=$?
    validate_path "$_carg_ES_ADD_ref_param"
    file_name=$?

    if [ $cont_name -ne 0 ] && [ $file_name -ne 0 ]; then
      _attach_errormsg "Illegal name"
      return 1
    fi

    path="${AWSTORE_DIR}/${_carg_ES_ADD_ref_param}.img"
    if [ $cont_name -eq 0 ] && [ -f "$path" ]; then
      # it's a container
      is_internal=true
    fi

    if [ $file_name -eq 0 ] && [ -f "${_carg_ES_ADD_ref_param}" ]; then
      # it's a file
      path="${_carg_ES_ADD_ref_param}"
      is_internal=false
    fi

    if [ -z "$is_internal" ]; then
      _attach_errormsg "Cannot find storage to attach (neither file nor container)"
      return 1
    fi
  fi

  # add special parameter
  carg_set_param "ES_ADD" "path" "${path}"

  return 0
}

function check_ES() {

  if [ -z $_carg_ES_MODE_param ]; then
    _attach_errormsg "Undefined extstore command"
    return 1
  fi

  return 0
}

function parse__RUN() {
  local res=0

  if [ ! -z $_carg__MODE_param ] && [ "$_carg__MODE_param" != "run" ]; then
    return 1
  fi

  _carg_chain_parse "--wait-w? name" "RUN"
  res=$?

  if [ -z $_carg__MODE_param ]; then
    carg_set_param "" "MODE" "run"
  fi

  return $res
}

function parse_RUN_name() {
  local cname=$1
  local clink=$2
  local name=$3
  local prev_flag=$4
  local prev_flag_dist=$5

  if ! validate_cont_name $name; then
    _attach_errormsg "Illegal name"
    return 1
  fi

  echo HIT "$cname" $clink $name
  if [ ! -d "$DB_DIR/$name" ]; then
    _attach_errormsg "Container does not exists"
    return 1
  fi

  carg_set_param "$cname" $clink $name

  return 0
}


function check_RUN() {
  return 0
}

_carg_COMMAND_arg_param=
function parse_COMMAND_arg() {
  local cname=$1
  local clink=$2
  local arg=$3

  _carg_COMMAND_arg_param="$_carg_COMMAND_arg_param $arg"
  # carg_set_param "$cname" $clink $arg
}

function check_COMMAND() {
  return 0
}

function parse_SYNC_path_local() {
  local cname=$1
  local clink=$2
  local path=$(realpath $3)

  if [ ! -f $path ] && [ ! -d $path ]; then
    _attach_errormsg "Provide correc file or directory path."
    return 1
  fi

  carg_set_param "$cname" $clink $path

  return 0
}

_carg_SYNC_path_remote_param=/usr/local/bin/
function parse_SYNC_path_remote() {
  local cname=$1
  local clink=$2
  local path="$3"

  if ! validate_path "$path"; then
    _attach_errormsg "Incorrect path: $path"

    return 1
  fi

  carg_set_param "$cname" $clink $path
  return 0
}

# check main chain:
function check_() {

  if [ -n "$_carg__help_param" ] || [ -n "$_carg__help_flag" ]; then
    print_help
  elif [ -z $_carg__MODE_param ]; then
    echo "Wrong syntax"
    echo "    type '--help' for help"
    return 1
  fi

  return 0
}


function check_SYNC() {
  return 0
}



function main() {
  local res=0
  # Prse arguments, if error accounted returns non-0 what terminates script (set -e)
  _carg_chain_parse "help? --help-h? MODE? CREATE? RUN?"

  case $_carg__MODE_param in
    create)
      #echo "create:
      # '${_carg_CREATE_device_flag}':
      # ${_carg_CREATE_dev_name_param}
      # '${_carg_CREATE_file_path_param}'
      # ${_carg_CREATE_extr_size_param}
      # ${_carg_CREATE_yesno_param} ${_carg_CREATE_kelner_param} ${_carg_CREATE_initramfs_param} ${_carg_CREATE_name_flag} ${parse_CREATE_cont_name_param}"
      #--device-d? dev_name? file_path extr_size? --imgboot-i yesno kelner? initramfs? --name-n? cont_name?" "create
      local cont_name=

      if [ ! -z ${_carg_CREATE_name_flag} ]; then
        cont_name=${_carg_CREATE_cont_name_param}
      else
        cont_name=$(basename $(mktemp --tmpdir=${AWSTORE_DIR} --suffix=.img) ".img")
      fi

      op_create $cont_name
      op_run $cont_name 1
    ;;
    run)
      op_run ${_carg_RUN_name_param}
    ;;
    command)
      # echo "Command: " $_carg_COMMAND_arg_param
      load_containersettings
      op_gcommand
    ;;
    sync)
      # echo "Sync: " $_carg_SYNC_path_local_param $_carg_SYNC_path_remote_param "$_carg_SYNC_reverse_flag"
      load_containersettings
      op_sync
    ;;
    console)
      load_containersettings
      op_enter
    ;;
    ls)
      check_environment

      load_containersettings || res=$?
      op_list
    ;;
    stop)
      load_containersettings
      stop_machine && rm_lock_file || res=$?

      if [ $res -ne 0 ]; then
        echo "Errors has been encountered"
        return $res
      fi

      if [ -n "$(echo ${_CONTAINER_NAME} | grep -e '^tmp\.')" ]; then
        echo "Tempolary container has been removed"
        op_remove ${_CONTAINER_NAME}
      fi
    ;;
    waitfor)
      load_containersettings
      op_waitfor || res=$?
    ;;
    es)
      case $_carg_ES_MODE_param in
        ls)
          echo "External storage list: "
          if [ "${_carg_es_ls_full_flag}" == "1" ]; then
            ls -l "${EXTSTORE_DIR}"
          else
            ls "${EXTSTORE_DIR}"
          fi
        ;;
        add)
          # echo "add ${_carg_ES_ADD_ref_param} ${_carg_ES_ADD_size_param}: ${_carg_ES_ADD_path_param}"
          if [ -n "${_carg_ES_ADD_size_param}" ]; then
            prepare_usbstick "${_carg_ES_ADD_path_param}" ${_carg_ES_ADD_size_param}
          fi

          insert_usbstick "${_carg_ES_ADD_path_param}"
        ;;
        eject)
          # issues: does not work
          remove_usbstick
        ;;
      esac
    ;;
    init)
      exit_if_not_root

      echo "Initializing $SCRIPT_BASE database and storage"
      init

      exit $?
    ;;
  esac

  return 0
}

main
exit $?
