#!/bin/bash
# Imperfect sync, some times under some circumstances
# it might not synchronize :)
# Generated by chatGPT, to be combined
# with 'alphawrap' ('-w' flag of 'sync' command)

# Configuration
SOURCE_DIR="alpha-wrap/share/"

# Function to perform rsync
sync_dirs() {
    echo "SYNCING $(date)"
    ./alpha-wrap/alpha-wrap sync $SOURCE_DIR
}

# Initial sync

TSTAMP=$(date +%s)
TDIFF=
# Monitor the source directory for changes
inotifywait -m -r -e modify,create,delete,move "$SOURCE_DIR" --format '%w%f' | while read FILE
do
    if [[ "$FILE" =~ ^.*~$ ]]; then
      continue
    fi

    TDIFF=$(( $(date +%s) - $TSTAMP ))

    if [ $TDIFF -lt 4 ]; then
      continue
    fi

    sleep 0.2
    sync_dirs
    TSTAMP=$(date +%s)
done

