#!/bin/sh

[ -n "$PRETEND" ] && $(echo "$PRETEND" | tr '[:upper:]' '[:lower:]' | grep -Eq '^(y|yes|1|on)$') && \
        RUN="echo 'Now we shall run:'" || RUN=""

[ -n "$DEBUG" ] && $(echo "$DEBUG" | tr '[:upper:]' '[:lower:]' | grep -Eq '^(y|yes|1|on)$') && \
        set -xe || set -e

# functions:
get_inspiration_word() {
  local word="inspiration"
  local skip_words=8
  local quotation=

  while [ $skip_words -gt -100 ]; do
    quotation=$(fortune | sed -e s/\\\\/\\\\\\\\/g -e s/\"/\\\\\"/g -e s/\'/\\\\\'/g | tr '\n' ' ' | tr "," ' ' | xargs)

    if [ -z "$quotation" ]; then
      # strangely no output from fortune, just quit function
      break
    fi

    for w in $quotation; do
      if [ $(echo -n $w | wc -c) -gt 3 ] && [ $skip_words -lt 1 ]; then
        word=$w
        skip_words=-100
        break
      fi
      skip_words=$((skip_words-1))
    done
  done

  echo -n $word
}

# texts:

present_ntp_notification() {
  local res=0
  cat <<EOF
No NTP service detected. The system may not have the correct time, which is
essential for SSL/TLS connections and proper functionality.

Do you wish to continue?
EOF

  read -p "    'yes' or 'y' to continue anyway: " choose
  echo "$choose" | tr '[:upper:]' '[:lower:]' | grep -Eq '^(y|yes|affirmative)$' || res=$?

  return $res
}

present_hostname_inspiration_option() {
  local res=0
  cat <<EOF
It's time to setup hostname, if you have no clue what to choose, type
'inspiration'. 'setup-finish' will pick some random words from random
quotations that can hopefully inspire you to come up with a name.

(if you don't need inspiration just hit ENTER)
(to serve inspiration words package 'fortune' will be automatically
 added)

EOF

  read -p "    type 'inspiration': " choose
  $(echo "$choose" | tr '[:upper:]' '[:lower:]' | grep -Eq '^inspiration$') || res=$?

  return $res
}


setup_hostname_with_inspiration() {
  local res=0

  echo -e "Inspiration words are: \n     - $(get_inspiration_word)\n     - $(get_inspiration_word)\n     - $(get_inspiration_word)\n"
  read -p "    Enter hostname (or hit ENTER for more inspiration words): " choose

  if [ -n "$choose" ]; then
    $RUN setup-hostname "$choose" || res=$?

    return $res
  fi

  return 1
}

present_passwd_upd() {
cat <<EOF
In the next step, the 'root' account will be disabled, and a password
will be set for the 'master' user.
EOF
}

check_ntp() {
  local res=

  local runn_ntp=""
  local aval_ntp=""

  # search for NTP services
  IFS=$' '; for ntp_srv in $(echo "ntpd chronyd openntpd"); do
    service ${ntp_srv} status &> /dev/null; res=$?

    case $res in
      0) # service running
        runn_ntp="${runn_ntp} ${ntp_srv}" ;;
      3)
        aval_ntp="${aval_ntp} ${ntp_srv}" ;;
      *) # service not found
        ;;
    esac
  done

  if [ -z "$runn_ntp" ]; then
    IFS=$' '; for ntp_srv in $(echo "${aval_ntp}"); do
      service "$ntp_srv" start
      runn_ntp=$ntp_srv
      break
    done
  fi

  [ -n "$runn_ntp" ] && res=0 || res=$?
  return $res
}

# main

trap 'echo -e "\n\n'$(basename $0)' terminated by user.\n"; exit 1' SIGINT SIGTERM

  if ! check_ntp; then
    # exit if 'not yes'
    present_ntp_notification || return 0
  fi

    # set repository:
  $RUN setup-apkrepos -c && echo ""

  $RUN setup-keymap && echo ""
  $RUN setup-timezone && echo ""

  if present_hostname_inspiration_option; then
    $RUN apk add fortune

    while ! setup_hostname_with_inspiration; do :; done
  else
    $RUN setup-hostname
  fi

  rc-update add hostname boot
  #service hostname status && \
  #  service hostname restart || \
  #  service hostname start

  present_passwd_upd
  while true; do $RUN passwd master && break || true; done
  $RUN passwd -l root

  $RUN rc-update del message default
  $RUN chmod -x /etc/profile.d/message

  echo "Setup finished, it's advised to reboot system"

exit 0
